server:
  port: 8002
spring:
  application:
    name: custom2    # 指定发布的微服务名（以后调用时，只需该名称即可访问该服务）
  datasource:
    data-password: dbadmin
    data-username: root
   #url: jdbc:mysql://192.168.0.118/zcfunding?useUnicode=true&characterEncoding=utf-8&tinyInt1isBit=false
    url: jdbc:mysql://localhost/liu?useUnicode=true&characterEncoding=utf-8&tinyInt1isBit=false
eureka:
#更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置。
  instance:
    lease-renewal-interval-in-seconds: 10          # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30      # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
#    healthcheck:
#        enabled: true   # 开启健康检查（依赖spring-boot-starter-actuator）
#        要与eureka:
#             server:
#               enable-self-preservation: false
#               eviction-interval-timer-in-ms: 4000  中的配置 配合使用，单独使用会报错
    serviceUrl:
        defaultZone: http://localhost:8000/eureka/       #注册中心地址
# 开启断路由功能   很重要 ，不能漏掉
feign:
  hystrix:
    enabled: true
